version: '3.9'

services:
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - data_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: './Dockerfile'
    working_dir: /opt/app/
    volumes:
      - .:/opt/app
      - data_bundle:/usr/local/bundle/
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  data_bundle:
  data_postgres:
